baseURL = "https://www.eecis.udel.edu/~ajbrock/"
languageCode = "en-us"
title = "Brockmeier - CNIEL - University of Delaware"
sectionPagesMenu = "main"
CanonifyURLs = true

[params]
    css = "css/style.css"